# Generated by Django 5.1 on 2024-09-01 09:10

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosformulario',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datosformulario',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'invalid': 'Por favor, introduce un número de teléfono válido.'}, max_length=128, region='ES'),
        ),
    ]
