# Generated by Django 5.1 on 2024-09-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_datosformulario_fecha_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosformulario',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
