# Generated by Django 5.1 on 2024-09-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_datosformulario_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosformulario',
            name='fecha_envio',
        ),
        migrations.RemoveField(
            model_name='datosformulario',
            name='ip_address',
        ),
    ]
