# Generated by Django 5.1 on 2024-09-01 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_remove_datosformulario_fecha_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosformulario',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datosformulario',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
